### ISSUE TITLE
v1.1.3 Git disappears from VCS menu in PyCharm

### ISSUE THREAD

**Issue by skykit-krishokanson** [PavlikPolivka/gitcleaner#11]
Upgraded to v1.1.3.  Totally lost Git option on my VCS menu.  Disable plugin and it comes back.

**Comment by JavierSegoviaCordoba** [comment]
Android Studio 3.6.1 too but I can't get it anymore, even reinstalling.

**Comment by primozi** [comment]
There's a pull request that fixes issue in Android Studio ( #10 ), that will most likely fix PyCharm as well.

**Comment by primozi** [comment]
@skykit-krishokanson, could you please re-check if it works with latest PyCharm (2020.1.1)?
It looks like it works for me, but I don't have any python projects to really test it.
