### ISSUE TITLE
Can this be built for IntelliJ IDEA? 

### ISSUE THREAD

**Issue by beirtipol** [PavlikPolivka/gitcleaner#12]
Looks like a great plugin, but I only get the option for installation in PyCharm

**Comment by PavlikPolivka** [comment]
I definately run it in IDEA. 
What idea version are you running?

Pavel
GitHub <notifications@github.com> wrote:
“Looks like a great plugin, but I only get the option for installation in PyCharm”

**Comment by beirtipol** [comment]
Running 2019.3.1 Ultimate

**Comment by beirtipol** [comment]
Oh that's weird, it now shows up in intellij in a new session. Sorry for
the noise!
