### ISSUE TITLE
[Suggest] Prevent delete un-merged branch

### ISSUE THREAD

**Issue by alantang888** [PavlikPolivka/gitcleaner#2]
Hello, can you add a option to keep the un-merged branch instead of delete it then show a notification? Sometime that small notification very easy to ignored.

**Comment by PavlikPolivka** [comment]
Hi.
I am not sure if unmerged info is easily obtainable. I will look into it I am in the middle of moving so I do not have that much time these days so no promises.

Proposed solution:

When listing branches that can be deleted all of them are checked by default. This includes unmerged branhcnes. Easiest would be to list those branches but do not check them by default.

**Comment by alantang888** [comment]
I see. Because there is a small notification popup when the unmerged branch is deleted. I though that is created by this plug-in.

**Comment by PavlikPolivka** [comment]
I submitted new version to JetBrains repository. 
Should be released within couple of business days.

**Comment by alantang888** [comment]
Thanks a lot!!
