### ISSUE TITLE
Plugin v1.1.3 crashes in Android Studio 3.6.1

### ISSUE THREAD

**Issue by primozi** [PavlikPolivka/gitcleaner#9]
Issue is due to AS only recognizing class files versions up to 52 (Java 8), but plugin was compiled using class file version 55 (Java 11).
More details are in the file [gitcleaner_error.txt](https://github.com/PavlikPolivka/gitcleaner/files/4321294/gitcleaner_error.txt).

**Comment by mgoyanes** [comment]
Can confirm that it also crashes
Android Studio 4.1 Canary 2
Build #AI-193.6494.35.41.6264773, built on March 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64

One strange thing is that the plugin crashes and makes the Git entry menu from the VCS menu disappear.

**Comment by mgoyanes** [comment]
Any update on this?

**Comment by primozi** [comment]
Still waiting for PR to be merged and then new version uploaded by @PavlikPolivka. 
If you want, you can pull changes from PR and build on your own.
